# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class P2pTunnel < Formula
  desc "Expose localhost to the internet. P2P alternative to ngrok."
  homepage "https://github.com/mihir-kanzariya/p2p-tunnel"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v0.4.0/p2p-tunnel_darwin_amd64.tar.gz"
      sha256 "697d85c7deec1feeaf2c13574828810375ade499f21645f080479f2088beb6f1"

      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v0.4.0/p2p-tunnel_darwin_arm64.tar.gz"
      sha256 "6a65683d255accd2118fab54c2b4dd5d577fdfc880a0eb57559e79c73b93e3a0"

      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v0.4.0/p2p-tunnel_linux_amd64.tar.gz"
      sha256 "02172cede683025e139b0fa7b2e8484aa1519928c77a7bbfe2079c4f537de873"
      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v0.4.0/p2p-tunnel_linux_arm64.tar.gz"
      sha256 "6dbe8a14a8e7fb9f0e5c0fdff29d7ca1c9e7b8a446a3b363b4042004462a5a46"
      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
  end

  test do
    system "#{bin}/p2p-tunnel", "--help"
  end
end
