# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class P2pTunnel < Formula
  desc "Expose localhost to the internet. P2P alternative to ngrok."
  homepage "https://github.com/mihir-kanzariya/p2p-tunnel"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v1.0.0/p2p-tunnel_darwin_amd64.tar.gz"
      sha256 "7cdd565043254627343984f9fe6d8bb4a67603fd315bbf20b95ef6a714e30335"

      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v1.0.0/p2p-tunnel_darwin_arm64.tar.gz"
      sha256 "83d22d063a175db85302c7bb12f96434dfb9c49b739f438ff0fb86368d3e19b1"

      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v1.0.0/p2p-tunnel_linux_amd64.tar.gz"
      sha256 "408addcfb3c844b274fd893de282111d9c12d2d5ca6f1966dbd68da97a497a5b"
      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihir-kanzariya/p2p-tunnel/releases/download/v1.0.0/p2p-tunnel_linux_arm64.tar.gz"
      sha256 "3361060b5c2c540dd607b5b3c34cb0e771d2e0da3cbd100294a3eeca0a1720e9"
      define_method(:install) do
        bin.install "p2p-tunnel"
      end
    end
  end

  test do
    system "#{bin}/p2p-tunnel", "--help"
  end
end
